# Generated by Django 4.2.1 on 2023-07-23 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_date", models.DateField(blank=True, null=True)),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "product_name1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("qty1", models.CharField(blank=True, max_length=10, null=True)),
                ("rate1", models.CharField(blank=True, max_length=10, null=True)),
                ("total1", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="create_invoice",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
