# Generated by Django 4.2.1 on 2023-07-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="Abc_XYZ_NONE",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
