# Generated by Django 4.2.1 on 2023-07-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_app", "0002_invoice_abc_xyz_none"),
    ]

    operations = [
        migrations.RemoveField(model_name="invoice", name="Abc_XYZ_NONE",),
    ]
